spring.application.name=open-banking-service
server.port=8082

#Persistance
spring.datasource.url=jdbc:postgresql://localhost:5432/home_banking
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl.auto=update

#Enable Banking
enablebanking.api.base-url=https://api.enablebanking.com
enablebanking.api.redirect-url=https://localhost:8084/api/open-banking/callback

#Secrets
spring.config.import=optional:file:src/main/resources/keys/secrets.properties