server:
  port: 8090

spring:
  application:
    name: api-gateway
  config:
    import: classpath:keys/secrets.properties
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: transaction-service
              uri: http://transaction-service:8080
              predicates:
                - Path=/api/v1/transactions/**, /api/v1/transaction/**, /api/v1/transactions, /api/v1/categories/**, /api/v1/categories, /api/v1/category/**
            - id: account-service
              uri: http://account-service:8081
              predicates:
                - Path=/api/v1/account, /api/v1/account/**
            - id: auth-service
              uri: http://auth-service:8083
              predicates:
                - Path=/api/v1/auth/**
            - id: account-service-docs
              uri: http://account-service:8081
              predicates:
                - Path=/account-service/v3/api-docs
              filters:
                - RewritePath=/account-service/v3/api-docs, /v3/api-docs
            - id: transaction-service-docs
              uri: http://transaction-service:8080
              predicates:
                - Path=/transaction-service/v3/api-docs
              filters:
                - RewritePath=/transaction-service/v3/api-docs, /v3/api-docs
            - id: open-banking-service-docs
              uri: http://open-banking-service:8082
              predicates:
                - Path=/open-banking-service/v3/api-docs
              filters:
                - RewritePath=/open-banking-service/v3/api-docs, /v3/api-docs
            - id: auth-service-docs
              uri: http://auth-service:8083
              predicates:
                - Path=/auth-service/v3/api-docs
              filters:
                - RewritePath=/auth-service/v3/api-docs, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: account-service
        url: /account-service/v3/api-docs
      - name: transaction-service
        url: /transaction-service/v3/api-docs
      - name: open-banking-service
        url: /open-banking-service/v3/api-docs
      - name: auth-service
        url: /auth-service/v3/api-docs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG